GET http://localhost:8080/students
Accept: application/json
Authorization: Basic max myPassword

###

POST http://localhost:8080/students/
Content-Type: application/json
Authorization: Basic max passme

{
  "userid": "it1000",
  "firstname": "Gerald",
  "lastname": "Aistleitner"
}

###

GET http://localhost:8080/passwords/passme

###
