GET http://localhost:8080/security/login
Content-Type: application/json

{
  "username": "aisge",
  "password": "geheim"
}

###

GET http://localhost:8080/security/info
Authorization: Bearer eyJraWQiOiJwcml2YXRlS2V5LnBlbSIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJ1cG4iOiJhaXNnZSIsImlzcyI6Imh0dHBzOi8vYXQuaHRsIiwiZ3JvdXBzIjpbInVzZXIiXSwiaWF0IjoxNTkxMjg3ODMyLCJhdXRoX3RpbWUiOjE1OTEyODc4MzIsImV4cCI6MTU5MTI4Nzk1MiwianRpIjoicXZnOGZ6M1hTTm84OGdVVW5XZTVZdyJ9.M9C_a6UuSnPh6Twb0QpfNDQEi_P-Av7Mqq_7I2ZMOWNLm7iHDkn8Ldy4veFuIGUFtbCwCQGDjgg37D4hi4Rnogbf1GRI_JbCOVSqOweP1DAXWC7ko1FdQZhHHoCi_DpG99EA5UGtnN_GNRsR1VijcWOA5uGTGA0cjlMANDSrLIhD4FhRHgfi8t1_YhGJHbEv6P0v6jbAPbc6jkHzdLPEPotQ3XAm0B-l9_IxkSoHBUJqh03YAJGs6gqEO_qU6gvzWtO8M2HHEEYnu47O2g1RrWyDUCjFuo4iNovUmdEzkF-Y0GY68MoAaUaBS515D7F0SnO_T-AOFVsutxZWDYT3FQ

###

GET http://localhost:8080/students
Authorization: Bearer eyJraWQiOiJwcml2YXRlS2V5LnBlbSIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwczovL2F0Lmh0bCIsImdyb3VwcyI6WyJ1c2VyIl0sImlhdCI6MTU5MTI4NzA2MCwiYXV0aF90aW1lIjoxNTkxMjg3MDYwLCJleHAiOjE1OTEyODcxODAsImp0aSI6IjU4STJDYXd6cl9SZWctUUJQXzUtS0EifQ.EkKVJlCDgRmd7-X_ZGsOPJapxh2mJD70EzUIOqT1IDuzkiv5vyPHTdidiTGWBGk276SzolAjQMpJESmmH_v-Ig420lxxhIsAtmZK5KtBiHRDSocKX0KVYgTa7A_avXc7xqjR2Hac8j2PFGeqPcD3H_pIJydPbFO1nwxPV2ePx8EvU9d-PsKMdaYd4nU5-gZTfaijkVnTchBLyHW82W-f4Zag0JWvJsLeg9JhiU1Q6plonIxzidehi3J9VI5z_Ns2k9LmB3qtw4ziTWxdFIbjFVPDlcnP8WQ-DbuQKmDOp-656NQzp_nvoZhV4bqdfnhpJ3n1q9s6WaeenlJqnLFtPQ

###